version: '3'
services:
  backend:
    restart: always
    build: /bp-backend/.
    ports:
      - 8080:8080
  frontend:
    build: /bp-frontend/.
    ports:
     - 22137:22137
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
 volumes:  


